
image: dahanna/python-alpine-package:tox-alpine

# https://docs.gitlab.com/ee/ci/yaml/includes.html#re-using-a-before_script-template
include:
  - project: 'gitlab-ci-yml-components/for-python'
    file: '.before_script.yml'


test:
  tags:
  - docker
  stage: test
  script:
  # If using an image that does not include tox, we will
  # need to pip install tox here.
  - pip install --upgrade wheel setuptools tox cookiecutter bumpversion

  - git --version || echo "git is not installed."
  - python --version
  - python2 --version || echo "python2 is not installed."
  - virtualenv --version || echo "virtualenv is not installed."
  - pip --version
  # When testing locally, we might not want to set tox sitepackages=true,
  # because the local machine might have all kinds of weird things in the
  # environment. But for continuous integration, we do want sitepackages=true,
  # because it allows us to use a Docker image with some packages already
  # installed to accelerate testing.
  - tox --version
  - uname --all
  - lsb_release --all || echo "lsb_release is not supported on this host."

  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

  - safe_sed () {
    sed --version > /dev/null 2>&1 && sed -i -- "$@" || sed -i "" "$@"
  }
  - start_tox=$(date +%s)
  # - tox --sitepackages
  - echo "tox tests took $(( $(date +%s) - start_tox)) seconds"
  - echo "Everything after pulling the Docker image took $(( $(date +%s) - right_after_pull_docker_image)) seconds total"

