language: python
dist: xenial
virt: lxd
python: '3.8'
cache: pip
env:
  global:
    - LD_PRELOAD=libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - ENV=cext
    - ENV=cffi
    - ENV=cython
    - ENV=matrix-cext
    - ENV=matrix-separate-cext
    - ENV=nose-pure
    - ENV=nose-pure-argparse
    - ENV=nose-pure-click
    - ENV=nose-pure-nocli
    - ENV=pure
    - ENV=pure-argparse
    - ENV=pure-click
    - ENV=pure-nocli
    - ENV=pure-private
    - ENV=pure-pylama
    - ENV=separate-cext
    - ENV=separate-cext-scm-osx-publish
    - ENV=separate-cffi
    - ENV=separate-cffi-scm-osx-publish
    - ENV=separate-cython
    - ENV=separate-cython-scm-osx-publish
    - ENV=separate-nose-pure
    - ENV=separate-pure
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install --upgrade --ignore-installed wheel setuptools tox cookiecutter bumpversion cffi
  - virtualenv --version
  - tox --version
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - git --version
  - ci/test.sh $ENV
  - cd python-nameless
  - git diff
  - |
    set -x
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      PR="pr${TRAVIS_PULL_REQUEST}-"
    else
      PR=""
    fi
    set +x
  - |
    if [ "$TRAVIS_BRANCH" -eq "master" ] && openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in ../publish-key.enc -out ~/.ssh/publish-key -d; then
      chmod u=rw,og= ~/.ssh/publish-key
      echo "Host github.com" >> ~/.ssh/config
      echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
      # ci/test.sh mangles tox.ini a bit for testing, so we need to undo that.
      git reset --hard
      bumpversion --new-version=1.$TRAVIS_JOB_NUMBER minor
      git push git@github.com:ionelmc/python-nameless.git -f HEAD:${PR}test-$ENV
    else
      echo Failed to get publish-key, running tests locally...
      set -x
      mkdir -p ~/.local/bin
      for name in pypy pypy3; do
        curl -sSf -o $name.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/$name.tar.bz2
        tar xjf $name.tar.bz2 --directory /
        rm $name.tar.bz2
        ln -s /opt/python/$name/bin/$name ~/.local/bin/$name
      done
      set +x
      # This is clunky, but hopefully soon https://github.com/pypa/pip/issues/6264 will be fixed so it won't matter anymore.
      if [ -e pyproject.toml ]; then
        echo "We have a PEP517 pyproject.toml, and the Travis PyPy installation has an old setuptools, so we cannot allow system site packages as long as pip has the build isolation bug."
        tox
      else
        echo "As long as we're not using PEP517, it's safe to use system site packages."
        tox --sitepackages
      fi
    fi
  - echo Done.

notifications:
  email:
    on_success: never
    on_failure: always
