image: python:3.7-alpine

{% if cookiecutter.ci_https_proxy != "no" -%}
variables:
  # HTTP_PROXY is used to pull docker images.
  HTTP_PROXY: {{cookiecutter.ci_https_proxy}}
  # HTTPS_PROXY is used to install Python packages such as tox.
  HTTPS_PROXY: {{cookiecutter.ci_https_proxy}}
  # If we don't include NO_PROXY, we will get "fatal unable to update url base from redirection"
  # when trying to fetch the gitlab-ci-token.
  NO_PROXY: 127.0.0.1,localhost,.lan,.local,.home,/var/run/docker.sock,{{cookiecutter.repo_hosting}}
  # If some of the links in your documentation require a special PEM to verify,
  # then sphinx -b linkcheck will fail without that PEM.
  # But setting REQUESTS_CA_BUNDLE to that PEM will cause other links to fail,
  # because the runner will only accept that PEM, not the defaults.
  # Therefore you will usually want to bundle all certificates together with
  # cat `python -c "import requests; print(requests.certs.where())"` ~/your.pem > ~/bundled.pem
  # REQUESTS_CA_BUNDLE: ci/name-of-your-ca-bundle.pem
{%- endif %}

default:
  before_script:
    - if [ -z ${SSH_PRIVATE_KEY+ABC} ]; then echo "SSH_PRIVATE_KEY is unset, so assuming you do not need SSH set up.";
      else
    # All of this will be skipped unless you set SSH_PRIVATE_KEY as a variable at https://{{ cookiecutter.repo_hosting }}/{{ cookiecutter.repo_username }}/{{ cookiecutter.repo_name }}/-/settings/ci_cd
    - if [ ${#SSH_PRIVATE_KEY} -le 5 ]; then echo "SSH_PRIVATE_KEY looks far too short, something is wrong"; fi
    - apk add openssh-client
    - echo "adding openssh-client took $(( $(date +%s) - start_time)) seconds"

    # ssh-agent -s starts the ssh-agent and then outputs shell commands to run.
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store.
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## We use -d because the version of tr on alpine does not recognize --delete.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir --parents ~/.ssh
    - ssh-keyscan -t rsa gitlab.sandia.gov >> ~/.ssh/known_hosts
    - fi

    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    #- git config --global user.email "{{ cookiecutter.email }}"
    #- git config --global user.name "{{ cookiecutter.full_name }}"

pages:
  script:
  - apk add git # probably do not want --no-cache
    # check-manifest, used in tox -e check, requires git.
  - pip3 install --upgrade pip
  - pip3 install tox
  - git --version
  - python3 --version
  - virtualenv --version
  - pip3 --version
  - tox --version
  - uname --all
  - lsb_release --all || echo "lsb_release is not supported on this host."
  - start_tox=$(date +%s)
  - tox
  - echo "tox tests took $(( $(date +%s) - start_tox)) seconds"
  - mv dist/docs/ public/
  artifacts:
    paths:
    - public
  only:
  - master
