image: alpine

variables:
  # HTTP_PROXY is used to pull docker images.
  HTTP_PROXY: {{cookiecutter.ci_https_proxy}}
  # HTTPS_PROXY is used to install Python packages such as tox.
  HTTPS_PROXY: {{cookiecutter.ci_https_proxy}}
  # If we don't include NO_PROXY, we will get "fatal unable to update url base from redirection"
  # when trying to fetch the gitlab-ci-token.
  NO_PROXY: 127.0.0.1,localhost,/var/run/docker.sock,{{cookiecutter.repo_hosting}}

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install tox
  - tox -e docs
  - mv dist/docs/ public/
  artifacts:
    paths:
    - public
  only:
  - master
